/**
 * QCC IT Report PDF Generator
 * Professional branded PDF reports using jsPDF + jspdf-autotable
 */
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

// ─── Brand constants ───────────────────────────────────────────────────────
const BRAND = {
  name: "QUALITY CONTROL COMPANY LIMITED",
  reg: "Reg. No. 3071",
  department: "Information Technology Department",
  primary: [0, 112, 60] as [number, number, number],      // deep green
  accent: [218, 165, 32] as [number, number, number],     // gold
  lightGray: [248, 248, 248] as [number, number, number],
  midGray: [230, 230, 230] as [number, number, number],
  darkGray: [80, 80, 80] as [number, number, number],
  black: [20, 20, 20] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
}

// ─── Helpers ───────────────────────────────────────────────────────────────
async function loadLogo(): Promise<string | null> {
  try {
    const res = await fetch("/images/qcc-logo.png")
    if (!res.ok) return null
    const blob = await res.blob()
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(reader.result as string)
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

function addPageHeader(
  doc: jsPDF,
  logoData: string | null,
  title: string,
  subtitle: string,
  pageW: number,
) {
  // Green header bar
  doc.setFillColor(...BRAND.primary)
  doc.rect(0, 0, pageW, 28, "F")

  // Gold accent stripe
  doc.setFillColor(...BRAND.accent)
  doc.rect(0, 28, pageW, 2, "F")

  // Logo
  if (logoData) {
    doc.addImage(logoData, "PNG", 8, 3, 22, 22)
  }

  // Company name
  doc.setFont("helvetica", "bold")
  doc.setFontSize(13)
  doc.setTextColor(...BRAND.white)
  doc.text(BRAND.name, logoData ? 34 : pageW / 2, 11, { align: logoData ? "left" : "center" })

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.text(`${BRAND.department}  •  ${BRAND.reg}`, logoData ? 34 : pageW / 2, 17, { align: logoData ? "left" : "center" })

  // Report title below bar
  doc.setFontSize(14)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(...BRAND.black)
  doc.text(title, pageW / 2, 40, { align: "center" })

  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(...BRAND.darkGray)
  doc.text(subtitle, pageW / 2, 47, { align: "center" })

  return 56 // next Y position
}

function addFooter(doc: jsPDF, generatedBy: string) {
  const pages = doc.getNumberOfPages()
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFillColor(...BRAND.primary)
    doc.rect(0, pageH - 8, pageW, 8, "F")

    doc.setFontSize(7)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(...BRAND.white)
    doc.text(
      `CONFIDENTIAL — Quality Control Company Limited  •  Generated by: ${generatedBy}  •  ${new Date().toLocaleString("en-GB")}`,
      pageW / 2,
      pageH - 3,
      { align: "center" }
    )
    doc.text(`Page ${i} / ${pages}`, pageW - 8, pageH - 3, { align: "right" })
  }
}

function addKPIRow(
  doc: jsPDF,
  items: Array<{ label: string; value: string; sub?: string; color?: [number, number, number] }>,
  y: number,
  pageW: number,
) {
  const count = items.length
  const boxW = (pageW - 16 - (count - 1) * 4) / count
  items.forEach((item, i) => {
    const x = 8 + i * (boxW + 4)
    const color = item.color || BRAND.primary
    // Box
    doc.setFillColor(...BRAND.lightGray)
    doc.roundedRect(x, y, boxW, 18, 2, 2, "F")
    doc.setDrawColor(...color)
    doc.setLineWidth(0.5)
    doc.roundedRect(x, y, boxW, 18, 2, 2, "D")
    // Left accent bar
    doc.setFillColor(...color)
    doc.roundedRect(x, y, 3, 18, 1, 1, "F")
    // Value
    doc.setFont("helvetica", "bold")
    doc.setFontSize(14)
    doc.setTextColor(...color)
    doc.text(item.value, x + boxW / 2 + 1.5, y + 8, { align: "center" })
    // Label
    doc.setFont("helvetica", "normal")
    doc.setFontSize(7)
    doc.setTextColor(...BRAND.darkGray)
    doc.text(item.label.toUpperCase(), x + boxW / 2 + 1.5, y + 13, { align: "center" })
    if (item.sub) {
      doc.setFontSize(6)
      doc.setTextColor(120, 120, 120)
      doc.text(item.sub, x + boxW / 2 + 1.5, y + 17, { align: "center" })
    }
  })
  return y + 22
}

function sectionTitle(doc: jsPDF, text: string, y: number, pageW: number) {
  doc.setFillColor(...BRAND.primary)
  doc.rect(8, y, pageW - 16, 7, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(...BRAND.white)
  doc.text(text.toUpperCase(), 12, y + 5)
  return y + 10
}

// ─── Main: IT Overview Report ──────────────────────────────────────────────
export interface ITReportLocation {
  location: string
  totalTickets: number
  resolvedTickets: number
  pendingTickets: number
  avgResolutionTime: number
  staffCount: number
  deviceCount: number
  repairRequests: number
}

export interface ITReportCategory {
  category: string
  count: number
  percentage: number
}

export interface ITReportTimeSeries {
  date: string
  tickets: number
  repairs: number
}

export interface ITReportPDFOptions {
  title?: string
  dateRange: string
  generatedBy: string
  location: string
  reportData: ITReportLocation[]
  categoryData: ITReportCategory[]
  timeSeriesData: ITReportTimeSeries[]
  totalStats: {
    totalTickets: number
    resolvedTickets: number
    pendingTickets: number
    avgResolutionTime: number
    staffCount: number
    deviceCount: number
    repairRequests: number
  }
}

export async function generateITReportPDF(opts: ITReportPDFOptions): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })
  const pageW = doc.internal.pageSize.getWidth()
  const logoData = await loadLogo()

  const resolutionRate =
    opts.totalStats.totalTickets > 0
      ? Math.round((opts.totalStats.resolvedTickets / opts.totalStats.totalTickets) * 100)
      : 0

  const subtitle = `Report Period: ${opts.dateRange}  •  Location: ${opts.location === "all" ? "All Locations" : opts.location}  •  Generated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`
  let y = addPageHeader(doc, logoData, opts.title || "IT OPERATIONS REPORT", subtitle, pageW)

  // ── KPI Section ──────────────────────────────────────────────────────────
  y = sectionTitle(doc, "Executive Summary — Key Performance Indicators", y, pageW)
  y = addKPIRow(
    doc,
    [
      { label: "Total Tickets", value: String(opts.totalStats.totalTickets), color: [37, 99, 235] },
      { label: "Resolved", value: String(opts.totalStats.resolvedTickets), color: [22, 163, 74] },
      { label: "Pending", value: String(opts.totalStats.pendingTickets), color: [234, 88, 12] },
      { label: "Resolution Rate", value: `${resolutionRate}%`, sub: "of all tickets", color: resolutionRate >= 75 ? [22, 163, 74] : [220, 38, 38] },
    ],
    y,
    pageW,
  )
  y = addKPIRow(
    doc,
    [
      { label: "Avg Resolution", value: `${opts.totalStats.avgResolutionTime.toFixed(1)}h`, sub: "per ticket", color: [124, 58, 237] },
      { label: "IT Staff", value: String(opts.totalStats.staffCount), color: [8, 145, 178] },
      { label: "Devices Managed", value: String(opts.totalStats.deviceCount), color: [161, 98, 7] },
      { label: "Repair Requests", value: String(opts.totalStats.repairRequests), color: [190, 18, 60] },
    ],
    y,
    pageW,
  )

  y += 2

  // ── Trend Summary Table ───────────────────────────────────────────────────
  if (opts.timeSeriesData.length > 0) {
    y = sectionTitle(doc, "Weekly Ticket Activity Trend", y, pageW)
    autoTable(doc, {
      startY: y,
      head: [["Week", "Tickets Created", "Repairs Logged"]],
      body: opts.timeSeriesData.map((d) => [d.date, d.tickets, d.repairs]),
      theme: "striped",
      headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold", fontSize: 8 },
      bodyStyles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { halign: "center" },
        2: { halign: "center" },
      },
      margin: { left: 8, right: 8 },
    })
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── Location Performance Table ───────────────────────────────────────────
  if (opts.reportData.length > 0) {
    // Check if we need a new page
    if (y > 220) { doc.addPage(); y = 16 }

    y = sectionTitle(doc, "Location Performance Breakdown", y, pageW)
    autoTable(doc, {
      startY: y,
      head: [["Location", "Staff", "Devices", "Total\nTickets", "Resolved", "Pending", "Resolution\nRate", "Avg Time\n(hrs)", "Repairs"]],
      body: opts.reportData.map((loc) => {
        const rate = loc.totalTickets > 0 ? Math.round((loc.resolvedTickets / loc.totalTickets) * 100) : 0
        return [
          loc.location,
          loc.staffCount,
          loc.deviceCount,
          loc.totalTickets,
          loc.resolvedTickets,
          loc.pendingTickets,
          `${rate}%`,
          `${loc.avgResolutionTime}h`,
          loc.repairRequests,
        ]
      }),
      foot: [[
        "TOTALS",
        opts.totalStats.staffCount,
        opts.totalStats.deviceCount,
        opts.totalStats.totalTickets,
        opts.totalStats.resolvedTickets,
        opts.totalStats.pendingTickets,
        `${resolutionRate}%`,
        `${opts.totalStats.avgResolutionTime.toFixed(1)}h`,
        opts.totalStats.repairRequests,
      ]],
      theme: "grid",
      headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold", fontSize: 7.5, halign: "center", valign: "middle" },
      footStyles: { fillColor: BRAND.accent, textColor: BRAND.black, fontStyle: "bold", fontSize: 8 },
      bodyStyles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      columnStyles: {
        0: { cellWidth: 45, fontStyle: "bold" },
        1: { halign: "center", cellWidth: 15 },
        2: { halign: "center", cellWidth: 18 },
        3: { halign: "center", cellWidth: 16 },
        4: { halign: "center", cellWidth: 18 },
        5: { halign: "center", cellWidth: 16 },
        6: { halign: "center", cellWidth: 20 },
        7: { halign: "center", cellWidth: 20 },
        8: { halign: "center", cellWidth: 16 },
      },
      margin: { left: 8, right: 8 },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 6) {
          const val = parseInt(String(data.cell.raw))
          if (val >= 90) data.cell.styles.textColor = [22, 163, 74]
          else if (val < 60) data.cell.styles.textColor = [220, 38, 38]
          else data.cell.styles.textColor = [180, 100, 0]
        }
      },
    })
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── Issue Category Analysis ───────────────────────────────────────────────
  if (opts.categoryData.length > 0) {
    if (y > 220) { doc.addPage(); y = 16 }

    y = sectionTitle(doc, "Issue Category Analysis", y, pageW)
    autoTable(doc, {
      startY: y,
      head: [["#", "Issue Category", "Ticket Count", "% of Total", "Volume Bar"]],
      body: opts.categoryData.map((cat, idx) => [
        idx + 1,
        cat.category,
        cat.count,
        `${cat.percentage}%`,
        "", // will be drawn as bar
      ]),
      theme: "striped",
      headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold", fontSize: 8 },
      bodyStyles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      columnStyles: {
        0: { cellWidth: 10, halign: "center" },
        1: { cellWidth: 75 },
        2: { cellWidth: 30, halign: "center" },
        3: { cellWidth: 25, halign: "center" },
        4: { cellWidth: 50 },
      },
      margin: { left: 8, right: 8 },
      didDrawCell: (data) => {
        if (data.section === "body" && data.column.index === 4) {
          const cat = opts.categoryData[data.row.index]
          if (!cat) return
          const maxPct = opts.categoryData[0]?.percentage || 1
          const barW = ((cat.percentage / maxPct) * (data.cell.width - 6))
          doc.setFillColor(...BRAND.primary)
          doc.roundedRect(data.cell.x + 2, data.cell.y + 2, barW, data.cell.height - 4, 1, 1, "F")
        }
      },
    })
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── Observations & Recommendations ──────────────────────────────────────
  if (y > 235) { doc.addPage(); y = 16 }
  y = sectionTitle(doc, "Observations & Recommendations", y, pageW)
  doc.setFillColor(...BRAND.lightGray)
  doc.roundedRect(8, y, pageW - 16, 28, 2, 2, "F")
  doc.setDrawColor(...BRAND.midGray)
  doc.roundedRect(8, y, pageW - 16, 28, 2, 2, "D")

  const obs: string[] = []
  if (resolutionRate < 70) obs.push(`• Resolution rate of ${resolutionRate}% is below the 70% target. Recommend increasing IT staff allocation or fast-tracking ticket triage.`)
  if (opts.totalStats.avgResolutionTime > 24) obs.push(`• Average resolution time of ${opts.totalStats.avgResolutionTime.toFixed(1)}h exceeds the 24-hour SLA target.`)
  if (opts.totalStats.pendingTickets > opts.totalStats.resolvedTickets) obs.push("• Pending tickets outnumber resolved tickets — backlog requires urgent attention.")
  if (obs.length === 0) obs.push("• All key performance indicators are within acceptable thresholds. Continue monitoring to sustain performance levels.")
  obs.push("• This report was auto-generated from live system data. Verify figures against source records where required.")

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(...BRAND.darkGray)
  let obsY = y + 6
  for (const line of obs) {
    const lines = doc.splitTextToSize(line, pageW - 24)
    doc.text(lines, 12, obsY)
    obsY += lines.length * 5 + 1
  }

  addFooter(doc, opts.generatedBy)

  const fileName = `IT-Report-${(opts.location === "all" ? "All-Locations" : opts.location).replace(/\s+/g, "-")}-${new Date().toISOString().split("T")[0]}.pdf`
  doc.save(fileName)
}

// ─── Main: Repair Analytics Report ────────────────────────────────────────
export interface RepairReportRow {
  id: string
  task_number?: string
  device_description?: string
  device_type?: string
  status: string
  priority?: string
  cost?: number
  location?: string
  service_provider_name?: string
  created_at: string
  estimated_completion?: string
  approved_date?: string
}

export interface RepairPDFOptions {
  dateRange: { start: string; end: string }
  generatedBy: string
  period: string
  totalTasks: number
  completedTasks: number
  inProgressTasks: number
  overdueTasks: number
  totalCost: number
  avgRepairTime: number
  repairs: RepairReportRow[]
}

export async function generateRepairReportPDF(opts: RepairPDFOptions): Promise<void> {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" })
  const pageW = doc.internal.pageSize.getWidth()
  const logoData = await loadLogo()

  const completionRate =
    opts.totalTasks > 0 ? ((opts.completedTasks / opts.totalTasks) * 100).toFixed(1) : "0"

  const subtitle = `Period: ${opts.period}  •  Generated: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`
  let y = addPageHeader(doc, logoData, "REPAIR & HARDWARE SERVICE REPORT", subtitle, pageW)

  // ── KPI Section ──────────────────────────────────────────────────────────
  y = sectionTitle(doc, "Executive Summary", y, pageW)
  y = addKPIRow(
    doc,
    [
      { label: "Total Tasks", value: String(opts.totalTasks), color: [37, 99, 235] },
      { label: "Completed", value: String(opts.completedTasks), color: [22, 163, 74] },
      { label: "In Progress", value: String(opts.inProgressTasks), color: [234, 88, 12] },
      { label: "Overdue", value: String(opts.overdueTasks), color: [220, 38, 38] },
      { label: "Completion Rate", value: `${completionRate}%`, sub: "of all tasks", color: parseFloat(completionRate) >= 75 ? [22, 163, 74] : [220, 38, 38] },
      { label: "Total Cost", value: `GHS ${opts.totalCost.toLocaleString("en-GH", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`, color: [161, 98, 7] },
      { label: "Avg Repair Time", value: `${opts.avgRepairTime.toFixed(1)}d`, sub: "calendar days", color: [124, 58, 237] },
    ],
    y,
    pageW,
  )

  y += 2

  // ── Status Breakdown Summary ─────────────────────────────────────────────
  const statusGroups: Record<string, number> = {}
  const costByStatus: Record<string, number> = {}
  opts.repairs.forEach((r) => {
    const s = r.status || "unknown"
    statusGroups[s] = (statusGroups[s] || 0) + 1
    costByStatus[s] = (costByStatus[s] || 0) + (r.cost || 0)
  })

  if (Object.keys(statusGroups).length > 0) {
    y = sectionTitle(doc, "Status Breakdown", y, pageW)
    autoTable(doc, {
      startY: y,
      head: [["Status", "Count", "% Share", "Total Cost (GHS)", "Avg Cost (GHS)"]],
      body: Object.entries(statusGroups)
        .sort((a, b) => b[1] - a[1])
        .map(([status, count]) => {
          const pct = opts.totalTasks > 0 ? ((count / opts.totalTasks) * 100).toFixed(1) : "0"
          const total = costByStatus[status] || 0
          const avg = count > 0 ? (total / count).toFixed(0) : "0"
          return [
            status.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
            count,
            `${pct}%`,
            total.toLocaleString("en-GH"),
            Number(avg).toLocaleString("en-GH"),
          ]
        }),
      theme: "striped",
      headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold", fontSize: 8 },
      bodyStyles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      columnStyles: {
        0: { cellWidth: 55 },
        1: { halign: "center", cellWidth: 25 },
        2: { halign: "center", cellWidth: 25 },
        3: { halign: "right", cellWidth: 40 },
        4: { halign: "right", cellWidth: 40 },
      },
      margin: { left: 8, right: 8 },
    })
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── Device & Location Breakdown ──────────────────────────────────────────
  const byLocation: Record<string, { count: number; cost: number; completed: number }> = {}
  opts.repairs.forEach((r) => {
    const loc = r.location || "Unknown"
    if (!byLocation[loc]) byLocation[loc] = { count: 0, cost: 0, completed: 0 }
    byLocation[loc].count++
    byLocation[loc].cost += r.cost || 0
    if (r.status === "completed") byLocation[loc].completed++
  })

  if (Object.keys(byLocation).length > 0) {
    if (y > 155) { doc.addPage(); y = 16 }
    y = sectionTitle(doc, "Repairs by Location", y, pageW)
    autoTable(doc, {
      startY: y,
      head: [["Location", "Tasks", "Completed", "Completion Rate", "Total Cost (GHS)"]],
      body: Object.entries(byLocation)
        .sort((a, b) => b[1].count - a[1].count)
        .map(([loc, data]) => {
          const rate = data.count > 0 ? ((data.completed / data.count) * 100).toFixed(1) : "0"
          return [loc, data.count, data.completed, `${rate}%`, data.cost.toLocaleString("en-GH")]
        }),
      theme: "striped",
      headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold", fontSize: 8 },
      bodyStyles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      columnStyles: {
        0: { cellWidth: 65 },
        1: { halign: "center", cellWidth: 25 },
        2: { halign: "center", cellWidth: 30 },
        3: { halign: "center", cellWidth: 35 },
        4: { halign: "right", cellWidth: 40 },
      },
      margin: { left: 8, right: 8 },
    })
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── Full Task Register ────────────────────────────────────────────────────
  doc.addPage()
  y = 16
  y = sectionTitle(doc, "Complete Repair Task Register", y, pageW)

  const statusColors: Record<string, [number, number, number]> = {
    completed: [22, 163, 74],
    in_transit: [234, 88, 12],
    with_provider: [37, 99, 235],
    overdue: [220, 38, 38],
    approved: [124, 58, 237],
    pending: [161, 98, 7],
  }

  autoTable(doc, {
    startY: y,
    head: [["#", "Task No.", "Device / Description", "Type", "Location", "Priority", "Status", "Cost (GHS)", "Days", "Created"]],
    body: opts.repairs.map((r, idx) => {
      const days =
        r.approved_date && r.estimated_completion
          ? Math.round(
              Math.abs(new Date(r.estimated_completion).getTime() - new Date(r.approved_date).getTime()) /
                (1000 * 60 * 60 * 24)
            )
          : ""
      return [
        idx + 1,
        r.task_number || `T-${r.id.slice(-5).toUpperCase()}`,
        (r.device_description || "—").slice(0, 40),
        r.device_type || "—",
        (r.location || "—").slice(0, 20),
        (r.priority || "normal").replace(/\b\w/g, (c) => c.toUpperCase()),
        r.status.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
        r.cost ? r.cost.toLocaleString("en-GH") : "—",
        days || "—",
        new Date(r.created_at).toLocaleDateString("en-GB"),
      ]
    }),
    theme: "grid",
    headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold", fontSize: 7, halign: "center" },
    bodyStyles: { fontSize: 7, cellPadding: 1.5 },
    alternateRowStyles: { fillColor: BRAND.lightGray },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 24 },
      2: { cellWidth: 55 },
      3: { cellWidth: 22 },
      4: { cellWidth: 30 },
      5: { cellWidth: 20, halign: "center" },
      6: { cellWidth: 28, halign: "center" },
      7: { cellWidth: 22, halign: "right" },
      8: { cellWidth: 12, halign: "center" },
      9: { cellWidth: 22, halign: "center" },
    },
    margin: { left: 8, right: 8 },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 6) {
        const row = opts.repairs[data.row.index]
        const col = statusColors[row?.status] || BRAND.darkGray
        data.cell.styles.textColor = col
        data.cell.styles.fontStyle = "bold"
      }
      if (data.section === "body" && data.column.index === 5) {
        const val = String(data.cell.raw).toLowerCase()
        if (val === "high" || val === "critical") data.cell.styles.textColor = [220, 38, 38]
        if (val === "medium") data.cell.styles.textColor = [180, 100, 0]
      }
    },
  })

  // Totals footer annotation
  const finalY = (doc as any).lastAutoTable.finalY + 4
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(...BRAND.black)
  doc.text(
    `Total Records: ${opts.repairs.length}  •  Total Cost: GHS ${opts.totalCost.toLocaleString("en-GH", { minimumFractionDigits: 2 })}  •  Avg Cost/Task: GHS ${opts.totalTasks > 0 ? (opts.totalCost / opts.totalTasks).toLocaleString("en-GH", { minimumFractionDigits: 0 }) : 0}`,
    8,
    finalY
  )

  addFooter(doc, opts.generatedBy)

  const fileName = `Repair-Report-${opts.dateRange.start}-to-${opts.dateRange.end}.pdf`
  doc.save(fileName)
}
